name: Run HelmUpgradeBot

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - test-action

jobs:
  helmupgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install HelmUpgradeBot
        run: |
          python -m pip install -e .
      - name: Dry-Run HelmUpgradeBot
        if: github.event_name == 'push' && github.ref == 'refs/heads/test-action'
        run: |
          API_TOKEN="${{ secrets.GITHUB_TOKEN }}" python -m HelmUpgradeBot \
            alan-turing-institute \
            hub23-deploy \
            Hub23 \
            hub23-chart \
            --dry-run \
            --verbose
      - name: Run HelmUpgradeBot
        if: github.event_name == 'schedule'
        run: |
          API_TOKEN="${{ secrets.GITHUB_TOKEN }}" python -m HelmUpgradeBot \
            alan-turing-institute \
            hub23-deploy \
            Hub23 \
            hub23-chart \
            --verbose
